version: '3'
services:
  mariadb:
    container_name: mariadb
    networks:
      - network42
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql/ 
    expose:
      - "3306"
    restart: always

  nginx:
    container_name: nginx
    networks:
      - network42
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    networks:
      - network42
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes: 
      - wordpress:/var/www/html
    expose:
      - "9000"

volumes:
  mariadb:
    driver: local
    driver_opts:
        type: volumes
        o: bind
        device: /home/vagrant/inception_data/mariadb
  wordpress:
    driver: local
    driver_opts:
        type: volumes
        o: bind
        device: /home/vagrant/inception_data/wordpress

networks:
  network42:
      driver: bridge
